package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_d//d:d.bzl", "d_source_library")

cc_library(
    name = "lib_2",
    srcs = ["lib_2.c"],
)

d_source_library(
    name = "lib_2_d_import",
    srcs = ["lib_2_import.di"],
)